/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ico.fes.sistemas.operativos;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author J-ALS
 */
public class Inicio extends javax.swing.JFrame  implements Runnable{
     String hora,minutos,segundos,ampm;
     Calendar calendario;
     Thread h1;
      Random rdm  =   new Random();
     ArrayList<Object> lista1   =   new ArrayList<>();
     JTextArea ta   =  new JTextArea();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
       
        initComponents();
        setLocationRelativeTo(this);
        h1  =   new Thread(this);
        h1.start();
        setVisible(true);
       
       
    }

    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonUno = new javax.swing.JButton();
        jButtonDos = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();
        jButtonCuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonCero = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonSiete = new javax.swing.JButton();
        jButtonOcho = new javax.swing.JButton();
        jButtonNueve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lbGraficas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jButtonUno.setText("1");
        jButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnoActionPerformed(evt);
            }
        });
        jButtonUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonUnoKeyPressed(evt);
            }
        });

        jButtonDos.setText("2");
        jButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosActionPerformed(evt);
            }
        });
        jButtonDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDosKeyPressed(evt);
            }
        });

        jButtonTres.setText("3");
        jButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTresActionPerformed(evt);
            }
        });

        jButtonCuatro.setText("4");
        jButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuatroActionPerformed(evt);
            }
        });

        jButtonCinco.setText("5");
        jButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoActionPerformed(evt);
            }
        });

        jButtonCero.setText("0");
        jButtonCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCeroMouseClicked(evt);
            }
        });
        jButtonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCeroActionPerformed(evt);
            }
        });
        jButtonCero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonCeroKeyTyped(evt);
            }
        });

        jButtonSeis.setText("6");
        jButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeisActionPerformed(evt);
            }
        });

        jButtonSiete.setText("7");
        jButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSieteActionPerformed(evt);
            }
        });

        jButtonOcho.setText("8");
        jButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOchoActionPerformed(evt);
            }
        });

        jButtonNueve.setText("9");
        jButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNueveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Presione cualquier número o botón");

        lblTime.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Programas", "Tamaño", "Privilegio", "Tiempo de ejecución"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCero)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUno)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDos)
                                .addGap(14, 14, 14)
                                .addComponent(jButtonTres))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCinco)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSeis)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonOcho)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCuatro)
                            .addComponent(jButtonNueve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lbGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCuatro)
                            .addComponent(jButtonCero)
                            .addComponent(jButtonUno)
                            .addComponent(jButtonDos)
                            .addComponent(jButtonTres))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeis)
                            .addComponent(jButtonSiete)
                            .addComponent(jButtonOcho)
                            .addComponent(jButtonNueve)
                            .addComponent(jButtonCinco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnoActionPerformed

        if (true) {
            evt.getActionCommand();
            jTable.setValueAt(evt.getActionCommand(), 1, 0);
            jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,1,3);
            
          
             for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 1, 2);
                }  
               for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 1, 1);
                }
        } else {
        }
        
        
    }//GEN-LAST:event_jButtonUnoActionPerformed

    private void jButtonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCeroActionPerformed
                    
        if (true){
             
              
                jTable.setValueAt(evt.getActionCommand(), 0, 0);
                jTable.setValueAt(hora +":" + minutos+":" + segundos, 0, 3);
                
                
                 for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 0, 2);
                } 
                   for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 0, 1);
                }
                
        }else{
            System.out.println("ADios...!");
        }
    }//GEN-LAST:event_jButtonCeroActionPerformed

    private void jButtonCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCeroMouseClicked

    private void jButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTresActionPerformed
           if (true) {
           jTable.setValueAt(evt.getActionCommand(),3, 0);
           jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,3,3);
         
           
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 3, 2);
                }  
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 3, 1);
                }
        } else {
        }
    }//GEN-LAST:event_jButtonTresActionPerformed

    private void jButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosActionPerformed
            if (true) {
            jTable.setValueAt(evt.getActionCommand(),2,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+ segundos,2,3);
             
           
             for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 2, 2);
                }  
               for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 2, 1);
                }
        } else {
        }
    }//GEN-LAST:event_jButtonDosActionPerformed

    private void jButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuatroActionPerformed
            if (true) {
            jTable.setValueAt(evt.getActionCommand(),4,0);
            jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,4,3);
           
          
             for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 4, 2);
                }  
             
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 4, 1);
                }
        } else {
                
                
        }
    }//GEN-LAST:event_jButtonCuatroActionPerformed

    private void jButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoActionPerformed
     if (true) {
            jTable.setValueAt(evt.getActionCommand(),5,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,5,3);
             
           
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 5, 2);
                }
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 5, 1);
                }
      
        } else {
                
                
        }
      
    }//GEN-LAST:event_jButtonCincoActionPerformed

    private void jButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeisActionPerformed
        if (true) {
            jTable.setValueAt(evt.getActionCommand(),6,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,6,3);
             
           jTable.setValueAt("0 MB", 6, 1);
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 6, 2);
                }  
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 6, 1);
                }
      
        } else {
                
                
        }
    }//GEN-LAST:event_jButtonSeisActionPerformed

    private void jButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSieteActionPerformed
                 if (true) {
            jTable.setValueAt(evt.getActionCommand(),7,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,7,3);
           
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 7, 2);
                } 
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 7, 1);
                }
      
        } else {
                
                
        }    }//GEN-LAST:event_jButtonSieteActionPerformed

    private void jButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOchoActionPerformed
                 if (true) {
            jTable.setValueAt(evt.getActionCommand(),8,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,8,3);
          
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 8, 2);
                }  
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 8, 1);
                }
      
        } else {
                
                
        }        
    }//GEN-LAST:event_jButtonOchoActionPerformed

    private void jButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNueveActionPerformed
             if (true) {
            jTable.setValueAt(evt.getActionCommand(),9,0);
             jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,9,3);
           
            for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 9, 2);
                }  
              for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-5)+5);
                    jTable.setValueAt(numAleatorio+" MB", 9, 1);
                }
      
        } else {
                
                
        }    }//GEN-LAST:event_jButtonNueveActionPerformed

    private void jButtonCeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCeroKeyTyped
          
       
    }//GEN-LAST:event_jButtonCeroKeyTyped

    private void jButtonCeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCeroKeyPressed
                char cero   =   evt.getKeyChar();
                
                if (Character.toString(cero).equals(KeyEvent.VK_NUMPAD0)) {
               jTable.setValueAt(cero, 0, 0);
               jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,0,3);
       
        } else {
        }
    }//GEN-LAST:event_jButtonCeroKeyPressed

    private void jButtonUnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUnoKeyPressed
                
                if (true) {
            jTable.setValueAt(evt.getID(), 1, 0);
            jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,1,3);
        } else {
        }
    }//GEN-LAST:event_jButtonUnoKeyPressed

    private void jButtonDosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDosKeyPressed
if (true) {
            jTable.setValueAt(evt.getID(), 3, 0);
            jTable.setValueAt(hora+ ":"+ minutos+":"+segundos,1,3);
        } else {
        }

    }//GEN-LAST:event_jButtonDosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
               
                       
            }
        });
    }
    
      private void PrimerProceso(java.awt.event.ActionEvent evt) {  
//        JOptionPane.showMessageDialog(this, "Se han iniciado los procesos!!!", "Simulador de Procesos FIFO", JOptionPane.INFORMATION_MESSAGE);        
        
        jTable.setValueAt("1", 0, 0);
        jTable.setValueAt("2", 1, 0);
        jTable.setValueAt("3", 2, 0);
        jTable.setValueAt("4", 3, 0);
        
        jTable.setValueAt("Chrome", 0, 1);
        jTable.setValueAt("Firefox", 1, 1);
        jTable.setValueAt("Word", 2, 1);
        jTable.setValueAt("Power Point", 3, 1);
        
        jTable.setValueAt("0 %", 0, 2);
        jTable.setValueAt("0 %", 1, 2);
        jTable.setValueAt("0 %", 2, 2);
        jTable.setValueAt("0 %", 3, 2);
        
        jTable.setValueAt("0 MB", 1, 0);
        jTable.setValueAt("0 MB", 1, 1);
        jTable.setValueAt("0 MB", 1, 2);
        jTable.setValueAt("0 MB", 1, 3);
        
      
        jTable.setValueAt(segundos+" seg", 0, 3);
        jTable.setValueAt(segundos+" seg", 1, 3);
        jTable.setValueAt(segundos+" seg", 2, 3);
        jTable.setValueAt(segundos+" seg", 3, 3);
        
        jTable.setValueAt("4", 0, 5);
        jTable.setValueAt("4", 1, 5);
        jTable.setValueAt("4", 2, 5);
        jTable.setValueAt("4", 3, 5);
        
        jTable.setValueAt("Listo", 0, 6);
        jTable.setValueAt("Listo", 1, 6);
        jTable.setValueAt("Listo", 2, 6);
        jTable.setValueAt("Listo", 3, 6);
        
//      segundos = tiempo1;
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //El porcetaje aleatorio del CPU
                for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*20);
                    jTable.setValueAt(numAleatorio+" %", 0, 2);
                }    

                //El rango aleatorio de la memoria ram
                for (int i=0;i<1000;i++){
                    int numAleatorio=(int)Math.floor(Math.random()*(15-10)+10);
                    jTable.setValueAt(numAleatorio+" MB", 0, 3);
                }
       
                jTable.setValueAt("Iniciado", 0, 6);
                jTable.setValueAt(String.valueOf(segundos) + " seg", 0, 4); 
                if(Integer.parseInt(segundos) <= 0) 
                {
                    jTable.setValueAt("Finalizado", 0, 6);                     
                    Toolkit.getDefaultToolkit().beep(); 
                    jTable.setValueAt("0 %", 0, 2);
                    jTable.setValueAt("0 MB", 0, 3);
 //                   Reloj.stop();
                      Calcular();
     //               SegundoProceso(evt);
                }
 //               segundos--; 
            }
        }; 
 //       Reloj = new javax.swing.Timer(delay, taskPerformer);
 //       Reloj.start(); 
    }
   
    public int aleatorio(int salida){
            Random rdm  =   new Random();
            for (int i = 1; i <4; i++) {
            int x = (int)rdm.nextInt()*9 + 1;
        }
         return salida;
       
    }
    
    public int tamaño(int tamaña1){
            for (int i = 1000; i <70000; i++) {
            int x = (int)rdm.nextInt();
        }
            return tamaña1;
    }
    
    public void Ordenar(){
        ArrayList lista =   new ArrayList();          
       lista.add(jTable.getColumnModel());
       
       
    }
 
                 

    
    public void Calcular(){
        Calendar calndario      =   new GregorianCalendar();
        Date fechaHoraActual    =   new Date();
        
        calndario.setTime(fechaHoraActual);
        ampm    =   calndario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if (ampm.equals("PM")) {
            int h   =   calndario.get(Calendar.HOUR_OF_DAY)-12;
            hora    =   h>9?"" + h:"0" + h; 
        } else {
            hora    =   calndario.get(Calendar.HOUR_OF_DAY)>9?"" + calndario.get(Calendar.HOUR_OF_DAY):"0" 
                     + calndario.get(Calendar.HOUR_OF_DAY);
        }
        minutos =   calndario.get(Calendar.MINUTE)>9?"" + calndario.get(Calendar.MINUTE):"0" 
                + calndario.get(Calendar.MINUTE);
        segundos    =   calndario.get(Calendar.SECOND)>9?"" + calndario.get(Calendar.SECOND):"0" 
                + calndario.get(Calendar.SECOND);
    }
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCero;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonCuatro;
    private javax.swing.JButton jButtonDos;
    private javax.swing.JButton jButtonNueve;
    private javax.swing.JButton jButtonOcho;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSiete;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lbGraficas;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
 Thread ct   =   Thread.currentThread();
        while (ct==h1) {            
            Calcular();
            lblTime.setText("   Time: " + hora + ":" + minutos + ":" + segundos + "" +ampm);
           
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            } 
        }
    }    
}
